Repository awslabs/mlspace, pull requests merged in 2024-06, with the labels that each got.

#117 Allow prefix selection for batch translate input
  frontend/src/entities/batch-translate/create/batch-translate-create.tsx
Labels: bug

#118 Backend updates for notebook instance constraints
  backend/src/ml_space_lambda/app_configuration/lambda_functions.py
  backend/src/ml_space_lambda/app_configuration/policy_helper/__init__.py
  backend/src/ml_space_lambda/app_configuration/policy_helper/notebook.py
  backend/src/ml_space_lambda/utils/mlspace_config.py
  backend/test/app_configuration/policy_helper/test_notebook.py
  backend/test/app_configuration/test_update_configuration.py
  backend/test/config/test_describe_config.py
  backend/test/utils/test_mlspace_config.py
  bin/mlspace-cdk.ts
  bin/scripts/config-helper.mjs
  lib/constants.ts
  lib/stacks/api/appConfiguration.ts
  lib/stacks/api/restApi.ts
  lib/stacks/iam.ts
  lib/utils/configTypes.ts
Labels: enhancement

#129 restore high contrast header
  frontend/src/App.tsx
  frontend/src/entities/batch-translate/create/batch-translate-create.tsx
  frontend/src/entities/batch-translate/detail/batch-translate-detail.tsx
  frontend/src/entities/configuration/activated-services-configuration.tsx
  frontend/src/entities/configuration/configuration.tsx
  frontend/src/entities/dataset/create/dataset-create.tsx
  frontend/src/entities/dataset/detail/dataset-detail.tsx
  frontend/src/entities/dataset/update/dataset-update.tsx
  frontend/src/entities/emr/create/emr-cluster-create.tsx
  frontend/src/entities/emr/detail/emr-clusters-detail.tsx
  frontend/src/entities/endpoint-config/create/endpoint-config-create.tsx
  frontend/src/entities/endpoint-config/detail/endpoint-config-detail.tsx
  frontend/src/entities/endpoint/create/endpoint-create.tsx
  frontend/src/entities/endpoint/detail/endpoint-detail.tsx
  frontend/src/entities/jobs/hpo/detail/hpo-job-detail.tsx
  frontend/src/entities/jobs/labeling/detail/labeling-job-detail.tsx
  frontend/src/entities/jobs/training/create/training-job-create.tsx
  frontend/src/entities/jobs/training/detail/training-job-detail.tsx
  frontend/src/entities/jobs/transform/create/transform-create.tsx
  frontend/src/entities/jobs/transform/detail/transform-detail.tsx
  frontend/src/entities/model/create/model-create.tsx
  frontend/src/entities/model/detail/model-detail.tsx
  frontend/src/entities/notebook/create/notebook-create.tsx
  frontend/src/entities/notebook/detail/notebook-detail.tsx
  frontend/src/entities/project/create/project-create.tsx
  frontend/src/entities/project/detail/project-detail.tsx
  frontend/src/entities/report/report.tsx
  frontend/src/entities/translate-realtime/translate-realtime.tsx
  frontend/src/shared/layout/content-layout.tsx
  frontend/src/shared/layout/home/home.tsx
  frontend/src/shared/layout/horizontal-line.tsx
  frontend/src/shared/layout/navigation/side-navigation.tsx
Labels: Ready For Review

#134 Creates graceful message for AccessDenied
  backend/src/ml_space_lambda/utils/common_functions.py
Labels: Ready For Review

#135 adding warning to save confirmation if user is disabling a service
  frontend/src/entities/configuration/activated-services-configuration.tsx
  frontend/src/entities/configuration/confirm-configuration-changes-modal.tsx
Labels: Ready For Review

#110 Activate/Deactivate services helper function
  backend/src/ml_space_lambda/app_configuration/lambda_functions.py
  backend/src/ml_space_lambda/app_configuration/policy_helper/active_service_policy_manager.py
  backend/src/ml_space_lambda/data_access_objects/app_configuration.py
  backend/src/ml_space_lambda/data_access_objects/resource_metadata.py
  backend/src/ml_space_lambda/enums.py
  backend/src/ml_space_lambda/initial_app_config/lambda_function.py
  backend/src/ml_space_lambda/project/lambda_functions.py
  backend/src/ml_space_lambda/utils/account_utils.py
  backend/src/ml_space_lambda/utils/common_functions.py
  backend/src/ml_space_lambda/utils/iam_manager.py
  backend/src/ml_space_lambda/utils/mlspace_config.py
  backend/src/ml_space_lambda/utils/resource_utils.py
  backend/test/app_configuration/test_get_configuration.py
  backend/test/app_configuration/test_update_configuration.py
  backend/test/config/test_describe_config.py
  backend/test/data_access_objects/test_resource_metadata.py
  backend/test/user/test_update_user.py
  backend/test/utils/test_iam_manager.py
  backend/test/utils/test_mlspace_config.py
  backend/test/utils/test_resource_utils.py
  frontend/src/entities/configuration/configuration.tsx
  frontend/src/entities/configuration/dynamic-configuration.tsx
  lib/stacks/api/appConfiguration.ts
  lib/stacks/iam.ts
  lib/utils/apiFunction.ts
Labels: Ready For Review

#133 Hides dynamic config options only for dynamic roles
  frontend/src/entities/configuration/dynamic-configuration.tsx
Labels: Ready For Review

#137 Docs updated for notebook dynamic role changes
  frontend/docs/.vitepress/config.mts
  frontend/docs/.vitepress/theme/custom.scss
  frontend/docs/.vitepress/theme/index.ts
  frontend/docs/admin-guide/getting-started.md
  frontend/docs/admin-guide/install.md
  frontend/package-lock.json
  frontend/package.json
Labels: Ready For Review

#131 App config documentation
  CONTRIBUTING.md
  README.md
  bin/scripts/config-helper.mjs
  frontend/docs/admin-guide/getting-started.md
  frontend/docs/admin-guide/initial-admin.md
  frontend/docs/admin-guide/install.md
  frontend/docs/user-guide/administration-pages.md
  frontend/docs/user-guide/batch-translation.md
  frontend/docs/user-guide/configuration.md
  frontend/docs/user-guide/datasets.md
  frontend/docs/user-guide/emr-clusters.md
  frontend/docs/user-guide/endpoint-configs.md
  frontend/docs/user-guide/endpoints.md
  frontend/docs/user-guide/hpo-jobs.md
  frontend/docs/user-guide/labeling-jobs.md
  frontend/docs/user-guide/models.md
  frontend/docs/user-guide/notebooks.md
  frontend/docs/user-guide/projects.md
  frontend/docs/user-guide/real-time-translation.md
  frontend/docs/user-guide/training-jobs.md
  frontend/docs/user-guide/user-preferences.md
  lib/constants.ts
  lib/stacks/iam.ts
Labels: Ready For Review

#138 Docs cleanup
  frontend/docs/.vitepress/config.mts
  frontend/docs/admin-guide/branding.md
  frontend/docs/admin-guide/byom-permissions.md
  frontend/docs/admin-guide/configure-cognito.md
  frontend/docs/admin-guide/getting-started.md
  frontend/docs/admin-guide/gt-workforce-keycloak.md
  frontend/docs/admin-guide/initial-admin.md
  frontend/docs/admin-guide/install.md
  frontend/docs/admin-guide/manual-s3-permissions.md
  frontend/src/entities/report/report.columns.ts
  lib/constants.ts
Labels: Ready For Review

#128 Dynamic roles initial app config policy update
  backend/src/ml_space_lambda/initial_app_config/lambda_function.py
  backend/src/ml_space_lambda/utils/common_functions.py
  backend/src/ml_space_lambda/utils/iam_manager.py
  backend/test/initial_app_config/test_populate_configuration.py
  backend/test/initial_app_config/test_update_dynamic_roles_with_notebook_policies.py
  backend/test/utils/test_common_functions.py
  backend/test/utils/test_iam_manager.py
  lib/stacks/iam.ts
  lib/stacks/infra/core.ts
Labels: Ready For Review

#153 Docs: Fix broken headers containing variables
  frontend/docs/admin-guide/getting-started.md
Labels: documentation, Ready For Review

#156 Docs: Minor fixes
  frontend/docs/admin-guide/install.md
Labels: documentation, Ready For Review

#159 Fixed test/linting trigger
  .github/workflows/test-and-lint.yml
Labels: Ready For Review

#160 Updated workflows for new development target
  .github/workflows/code/deploy.demo.yml
  .github/workflows/code/deploy.development.yml
  .github/workflows/code/test-and-lint.yml
  .github/workflows/docs/deploy.github-pages.yml
Labels: Ready For Review

#158 Bug: Fixed WYSIWYG editor so images don't overflow
  frontend/src/shared/util/rich-text-utils.scss
  frontend/src/shared/util/rich-text-utils.tsx
Labels: bug, Ready For Review

#170 Bug: ARNs for Instance contraint policies not being passed to lambdas correctly
  bin/mlspace-cdk.ts
  lib/stacks/infra/core.ts
Labels: bug

#178 Bug: instance constraint issues
  .github/workflows/test-and-lint.yml
  backend/src/ml_space_lambda/initial_app_config/lambda_function.py
  backend/test/app_configuration/test_update_configuration.py
  backend/test/initial_app_config/test_populate_configuration.py
  backend/test/initial_app_config/test_update_dynamic_roles_with_notebook_policies.py
  lib/stacks/iam.ts
Labels: Ready For Review
