Repository awslabs/mlspace, pull requests merged in 2024-04, with the labels that each got.

#53 Validation requirements too restrctive
  frontend/src/entities/jobs/hpo/create/training-definitions/training-job-definition.tsx
  frontend/src/entities/jobs/labeling/create/labeling-job-create.tsx
  frontend/src/entities/jobs/training/create/training-job-create.tsx
  frontend/src/entities/jobs/transform/create/transform-create.tsx
Labels: bug

#51 [bugfix] git hash fix position to bottom
  frontend/src/shared/layout/navigation/side-navigation.tsx
Labels: bug

#56 Fixed error when no query string parameters are sent when listing Dataset files
  backend/src/ml_space_lambda/dataset/lambda_functions.py
  backend/test/dataset/test_list_dataset_files.py
Labels: bug

#57 Dataset Fixes/Enhancements
  frontend/src/modules/dataset/dataset-browser.reducer.tsx
  frontend/src/modules/dataset/dataset-browser.tsx
  frontend/src/modules/dataset/dataset-selector.tsx
Labels: bug, enhancement

#63 Resolves eslint issue
  frontend/.eslintrc
  frontend/src/shared/validation/helpers/uri.ts
Labels: bug

#64 Display DatasetSelector warning when file(s) don't exist.
  backend/src/ml_space_lambda/dataset/lambda_functions.py
  frontend/src/entities/jobs/hpo/create/training-definitions/input-data-configuration.tsx
  frontend/src/entities/jobs/transform/create/transform-create.tsx
  frontend/src/modules/dataset/dataset-browser.reducer.tsx
  frontend/src/modules/dataset/dataset-selector.reducer.tsx
  frontend/src/modules/dataset/dataset-selector.tsx
  frontend/src/modules/dataset/dataset-selector.types.ts
  frontend/src/shared/model/transform.model.ts
Labels: enhancement
