Repository awslabs/mlspace, pull requests merged in 2024-05, with the labels that each got.

#75 [AIML-ADC-8258] Add automatic deployment to demo environment
  .github/workflows/demo-deploy.yml
  lib/utils/layers.ts
Labels: enhancement

#76 Add missing spaceing between action buttons
  frontend/src/entities/notebook/detail/notebook-detail.tsx
Labels: enhancement

#78 [AIML-ADC-8135] Add hook for debouncing
  .eslintrc
  frontend/src/entities/translate-realtime/translate-realtime.common.tsx
  frontend/src/entities/translate-realtime/translate-realtime.text.tsx
  frontend/src/modules/dataset/dataset-selector.tsx
  frontend/src/modules/textfilter/textfilter.tsx
  frontend/src/shared/util/hooks.ts
Labels: enhancement

#82 prevent breadcrumbs from reloading all of app layout
  frontend/src/App.tsx
  frontend/src/shared/layout/navigation/breadcrumbs.tsx
Labels: bug, enhancement

#74 add loading icons when background refreshing
  frontend/src/entities/batch-translate/detail/batch-translate-detail.tsx
  frontend/src/entities/emr/detail/emr-clusters-detail.tsx
  frontend/src/entities/endpoint/detail/endpoint-detail.tsx
  frontend/src/entities/jobs/hpo/detail/hpo-job-detail.tsx
  frontend/src/entities/jobs/labeling/detail/labeling-job-detail.tsx
  frontend/src/entities/jobs/training/detail/training-job-detail.tsx
  frontend/src/entities/jobs/transform/detail/transform-detail.tsx
  frontend/src/entities/notebook/detail/notebook-detail.tsx
  frontend/src/entities/project/detail/project-detail.tsx
  frontend/src/modules/table/table.tsx
  frontend/src/shared/util/hooks.ts
  frontend/src/shared/util/table-utils.tsx
Labels: enhancement

#80 make dataset table use serverFetch and proper loading action
  frontend/src/entities/dataset/dataset.actions.tsx
  frontend/src/entities/dataset/dataset.reducer.ts
  frontend/src/entities/dataset/dataset.tsx
Labels: enhancement

#100 Fixes Notebook Lifecycle Config Start Bug
  lib/stacks/infra/sagemaker.ts
Labels: bug

#96 fixes issues where datasets were listing incorrectly
  frontend/src/entities/dataset/dataset.reducer.ts
  frontend/src/entities/dataset/dataset.tsx
  frontend/src/modules/dataset/dataset-browser.tsx
  frontend/src/shared/util/hooks.ts
  frontend/src/shared/util/table-utils.tsx
Labels: bug
